version: "3.8"

services:
  mongo:
    image: "mongo"
    container_name: "the_plague_db"
    restart: always
    ports:
      - "8090:27017" # Exposing MongoDB on port 8090
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: SAUls364C9zrcti
    volumes:
      - mongo_data:/data/db # Persist MongoDB data

  the_plague_api: # Your application service
    image: "the-plague-api_image" # Specify the image name for your application
    container_name: "the_plague_api_container" # Specify the container name for your application
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080" # Exposing the application on port 8080
    environment:
      MONGO_DB_USERNAME: admin # Username for MongoDB
      MONGO_DB_PASSWORD: SAUls364C9zrcti # Password for MongoDB
      MONGO_DB_HOST: mongo # Hostname for the MongoDB service
      MONGO_DB_PORT: 27017 # Optional: specify the MongoDB port
      MONGO_DB_NAME: the_plague # Optional: specify the database name if needed
    depends_on:
      - mongo # Ensure mongo starts before the application

volumes:
  mongo_data: # Define the volume for MongoDB data
