version: "3.8"

services:
  the_plague_api:
    image: "the_plague_api:1.0.0"
    container_name: "the_plague_api_container"
    build:
      context: . # Path to your back-end source
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - the_plague_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

networks:
  the_plague_network:
    name: the_plague_network
    external: true
