version: "3.8"

services:
  the_plague_api:
    image: "the_plague_api:1.0.0"
    container_name: "the_plague_api_container"
    build:
      context: . # Path to your back-end source
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    networks:
      - the_plague_network

networks:
  the_plague_network:
    driver: bridge
