services:
  mongo:
    image: "mongo"
    container_name: "the_plague_db"
    restart: always
    ports:
      - 8090:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: SAUls364C9zrcti
